apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-echo-domain
  namespace: echo-server
spec:
  acme:
    email: mark@wilson.codes
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-echo-domain-private
    solvers:
    - dns01:
        digitalocean:
          tokenSecretRef:
            name: digitalocean-dns
            key: access-token